// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Numerics;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.Guidebook;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Lobby.UI.Roles;

/// <summary>
/// A generic locking selector.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class RequirementsSelector : BoxContainer
{
    private readonly RadioOptions<int> _options;
    private readonly StripeBack _lockStripe;
    private List<ProtoId<GuideEntryPrototype>>? _guides;
    private List<string>? _alternateTitles; // Omu

    public event Action<int>? OnSelected;
    public event Action<string?>? OnAlternateTitleSelected; // Omu
    public event Action<List<ProtoId<GuideEntryPrototype>>>? OnOpenGuidebook;

    public int Selected => _options.SelectedId;

    public RequirementsSelector()
    {
        RobustXamlLoader.Load(this);
        _options = new RadioOptions<int>(RadioOptionsLayout.Horizontal)
        {
            FirstButtonStyle = StyleClass.ButtonOpenRight,
            ButtonStyle = StyleClass.ButtonOpenBoth,
            LastButtonStyle = StyleClass.ButtonOpenLeft,
            HorizontalExpand = true,
        };
        //Override default radio option button width
        _options.GenerateItem = GenerateButton;

        _options.OnItemSelected += args =>
        {
            _options.Select(args.Id);
            OnSelected?.Invoke(args.Id);
        };

        var requirementsLabel = new Label()
        {
            Text = Loc.GetString("role-timer-locked"),
            Visible = true,
            HorizontalAlignment = HAlignment.Center,
            StyleClasses = {StyleClass.LabelSubText},
        };

        _lockStripe = new StripeBack()
        {
            Visible = false,
            HorizontalExpand = true,
            HasMargins = false,
            MouseFilter = MouseFilterMode.Stop,
            Children =
            {
                requirementsLabel
            }
        };

        Help.OnPressed += _ =>
        {
            if (_guides != null)
                OnOpenGuidebook?.Invoke(_guides);
        };

        // Omu start
        TitleOptions.OnItemSelected += args =>
        {
            TitleOptions.SelectId(args.Id);
            if (_alternateTitles == null)
                return;

            OnAlternateTitleSelected?.Invoke(args.Id == 0 ? null : _alternateTitles[args.Id - 1]);
        };
        // Omu end
    }

    /// <summary>
    /// Actually adds the controls.
    /// </summary>
    public void Setup(
        (string, int)[] items,
        string title,
        int titleSize,
        string? description,
        TextureRect? icon = null,
        List<ProtoId<GuideEntryPrototype>>? guides = null)
    {
        foreach (var (text, value) in items)
        {
            _options.AddItem(Loc.GetString(text), value);
        }

        Help.Visible = guides != null;
        _guides = guides;

        TitleLabel.Text = title;
        TitleLabel.MinSize = new Vector2(titleSize, 0f);
        TitleLabel.ToolTip = description;

        if (icon != null)
        {
            AddChild(icon);
            icon.SetPositionFirst();
        }

        OptionsContainer.AddChild(_options);
        OptionsContainer.AddChild(_lockStripe);
    }

    // Omu start
    /// <param name="lockedTitles">Titles whose requirements are not met, with the reason. They can't be selected.</param>
    public void SetupAlternateTitles(IReadOnlyList<string> titles,
        string? selected,
        IReadOnlyDictionary<string, FormattedMessage>? lockedTitles = null)
    {
        _alternateTitles = new List<string>(titles);

        TitleOptions.Clear();
        TitleOptions.AddItem(TitleLabel.Text ?? string.Empty, 0);

        // The job description followed by the reason for every locked title.
        var tooltipMessage = new FormattedMessage();
        if (!string.IsNullOrEmpty(TitleLabel.ToolTip))
            tooltipMessage.AddText(TitleLabel.ToolTip);

        var anyLocked = false;
        for (var i = 0; i < _alternateTitles.Count; i++)
        {
            var name = Loc.GetString(_alternateTitles[i]);
            if (lockedTitles == null || !lockedTitles.TryGetValue(_alternateTitles[i], out var reason))
            {
                TitleOptions.AddItem(name, i + 1);
                continue;
            }

            TitleOptions.AddItem(Loc.GetString("job-alt-title-locked", ("title", name)), i + 1);
            TitleOptions.SetItemDisabled(TitleOptions.GetIdx(i + 1), true);

            if (!tooltipMessage.IsEmpty)
            {
                tooltipMessage.PushNewline();
                tooltipMessage.PushNewline();
            }

            tooltipMessage.AddMarkupOrThrow(Loc.GetString("job-alt-title-locked-tooltip", ("title", FormattedMessage.EscapeText(name))));
            tooltipMessage.PushNewline();
            tooltipMessage.AddMessage(reason);
            anyLocked = true;
        }

        TitleOptions.MinSize = TitleLabel.MinSize;
        TitleOptions.ToolTip = TitleLabel.ToolTip;
        TitleOptions.TooltipSupplier = null;
        if (anyLocked)
        {
            var tooltip = new Tooltip();
            tooltip.SetMessage(tooltipMessage);
            TitleOptions.TooltipSupplier = _ => tooltip;
        }

        TitleLabel.Visible = false;
        TitleOptions.Visible = true;
        SelectAlternateTitle(selected);
    }

    public void SelectAlternateTitle(string? title)
    {
        if (_alternateTitles == null)
            return;

        var index = title == null ? -1 : _alternateTitles.IndexOf(title);
        TitleOptions.SelectId(index + 1);
    }
    // Omu end

    public void LockRequirements(FormattedMessage requirements)
    {
        var tooltip = new Tooltip();
        tooltip.SetMessage(requirements);
        _lockStripe.TooltipSupplier = _ => tooltip;
        _lockStripe.Visible = true;
        _options.Visible = false;
    }

    public void UnlockRequirements()
    {
        _lockStripe.Visible = false;
        _options.Visible = true;
    }

    private Button GenerateButton(string text, int value)
    {
        return new Button
        {
            Text = text,
            MinWidth = 90,
            HorizontalExpand = true,
        };
    }

    public void Select(int id)
    {
        _options.Select(id);
    }
}